#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: ro

  # Disable SSH in the installer, or packer will fail to connect and stop the install
  early-commands:
    - systemctl stop ssh

  network:
    network:
      version: 2
      ethernets:
        eth0:
          dhcp4: yes
          nameservers:
            addresses:
              - 1.1.1.1
              - 8.8.8.8

  apt:
    preserve_sources_list: false
    mirror-selection:
      primary:
        - country-mirror
        - arches: [default]
          uri: "http://archive.ubuntu.com/ubuntu"
    geoip: true

  storage:
    layout:
      name: direct
    swap:
      size: 0
    config:
      - type: disk
        id: disk0
        ptable: msdos
        wipe: superblock
        grub_device: true
      - type: partition
        id: root-partition
        device: disk0
        size: -1
        flag: boot

  identity:
    hostname: ${hostname}.local
    username: ${user.username}
    password: ${user.password}

  ssh:
    install-server: yes
    allow-pw: true

  user-data:
    disable_root: true

  late-commands:
    - sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=1/' /target/etc/default/grub
    - sed -i 's/^\(GRUB_CMDLINE_LINUX_DEFAULT\)=.*/\1="net.ifnames=0 modprobe.blacklist=floppy console=ttyS0,115200n8 no_timer_check edd=off"/' /target/etc/default/grub
    - sed -i '/^\/swap.img/d' /target/etc/fstab
    - rm -f /target/swap.img
